# Generated by Django 5.2 on 2026-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='league_level',
            field=models.CharField(choices=[('STEP_1', 'Step 1 (National League)'), ('STEP_2', 'Step 2 (National League North/South)'), ('STEP_3', 'Step 3 (Isthmian/Northern/Southern Premier)'), ('STEP_4', 'Step 4 (Isthmian/Northern/Southern Division One)'), ('STEP_5', 'Step 5 (Regional Leagues)'), ('STEP_6', 'Step 6 (County Leagues)'), ('STEP_7', 'Step 7 (Local Leagues)'), ('SUNDAY', 'Sunday League'), ('OTHER', 'Other')], default='SUNDAY', help_text='League level the club currently plays in.', max_length=10),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='location_postcode',
            field=models.CharField(default='', help_text="Postcode for club's location.", max_length=10),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='rss_feed_url',
            field=models.URLField(blank=True, help_text='RSS feed URL for club news (for news scraper).', max_length=500),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='location_postcode',
            field=models.CharField(default='', help_text="Postcode for player's location.", max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('BOTH', 'Both')], help_text='Preferred foot.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='youtube_highlight_url',
            field=models.URLField(blank=True, help_text='YouTube link to player highlights.', max_length=500),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='club_name',
            field=models.CharField(default='', help_text='Official name of the club.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='league',
            field=models.CharField(blank=True, help_text='League the club currently plays in.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City or region of the club.', max_length=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters (e.g., 1.85).', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='playing_level',
            field=models.CharField(choices=[('STEP_1', 'Step 1 (National League)'), ('STEP_2', 'Step 2 (National League North/South)'), ('STEP_3', 'Step 3 (Isthmian/Northern/Southern Premier)'), ('STEP_4', 'Step 4 (Isthmian/Northern/Southern Division One)'), ('STEP_5', 'Step 5 (Regional Leagues)'), ('STEP_6', 'Step 6 (County Leagues)'), ('STEP_7', 'Step 7 (Local Leagues)'), ('SUNDAY', 'Sunday League'), ('OTHER', 'Other')], default='SUNDAY', help_text='Current playing level (Step 1-7 or Sunday League).', max_length=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('CB', 'Centre Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CDM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CF', 'Centre Forward')], default='ST', help_text='Primary playing position.', max_length=3),
        ),
        migrations.AlterField(
            model_name='scoutprofile',
            name='region',
            field=models.CharField(default='', help_text='Primary region covered by the scout.', max_length=100),
        ),
    ]
