# Generated by Django 5.2 on 2026-01-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clubprofile_league_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the news item.', max_length=500)),
                ('link', models.URLField(help_text='Link to the full news article.', max_length=1000)),
                ('description', models.TextField(blank=True, help_text='Description or summary of the news item.')),
                ('published_date', models.DateTimeField(help_text='Date and time when the news was published.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added to our database.')),
                ('club', models.ForeignKey(help_text='The club this news item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='users.clubprofile')),
            ],
            options={
                'ordering': ['-published_date'],
                'unique_together': {('club', 'link')},
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('newsitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.newsitem')),
                ('target_position', models.CharField(blank=True, help_text="Target position(s) for the trial or recruitment (e.g., 'Striker', 'Midfielder').", max_length=100)),
                ('is_open', models.BooleanField(default=True, help_text='Whether the opportunity is still open for applications.')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-published_date'],
            },
            bases=('users.newsitem',),
        ),
    ]
