# Generated by Django 5.2 on 2026-01-20 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newsitem_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='Whether this club has a registered user account.'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='club_name',
            field=models.CharField(help_text='Official name of the club.', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='location_postcode',
            field=models.CharField(blank=True, help_text="Postcode for club's location.", max_length=10),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account (only if club signed up). Leave blank for admin-added clubs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
