# Generated by Django 5.2 on 2026-01-26 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clubprofile_is_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PLAYER', 'Player'), ('CLUB', 'Club'), ('SCOUT', 'Scout'), ('MANAGER', 'Manager'), ('FAN', 'Fan')], help_text='The role of the user in the system.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, help_text='Name of the club currently managing.', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of managerial experience.', null=True)),
                ('coaching_qualifications', models.TextField(blank=True, help_text='Coaching qualifications and certifications (e.g., UEFA B, FA Level 2).')),
                ('preferred_formation', models.CharField(blank=True, help_text='Preferred tactical formation (e.g., 4-4-2, 4-3-3).', max_length=50)),
                ('location_postcode', models.CharField(blank=True, help_text="Postcode for manager's location.", max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
