# Generated by Django 5.2 on 2026-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='available_for_club',
            field=models.BooleanField(default=False, help_text='Whether the player is looking for a club.'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='current_team',
            field=models.CharField(blank=True, help_text='Current team/club name.', max_length=100),
        ),
    ]
