# Generated by Django 5.2 on 2026-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_playerprofile_available_for_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a highlight video (MP4, AVI, MOV). Max size: 50MB.', null=True, upload_to='player_videos/'),
        ),
    ]
