# Generated by Django 5.2 on 2026-01-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_playerprofile_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='coaching_qualifications',
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text="List trophies, titles, and notable achievements (e.g., 'Isthmian League North Winner 2022')."),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='additional_badges',
            field=models.TextField(blank=True, help_text="Additional qualifications (e.g., 'FA Youth Award', 'Goalkeeping Level 2')."),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='availability',
            field=models.CharField(choices=[('EMPLOYED', 'Currently Employed'), ('OPEN', 'Open to Offers')], default='EMPLOYED', help_text='Current employment status.', max_length=20),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='career_history',
            field=models.TextField(blank=True, help_text="List previous clubs, roles, and dates (e.g., '2020-2022: First Team Manager at FC United')."),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='coaching_philosophy',
            field=models.TextField(blank=True, help_text="Describe your coaching style and philosophy (e.g., 'High pressing', 'Possession-based')."),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='current_role',
            field=models.CharField(blank=True, help_text='e.g., First Team Manager, Assistant Manager, U23 Coach.', max_length=100),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='games_managed',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of games managed.', null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='highest_qualification',
            field=models.CharField(choices=[('NONE', 'No Formal Qualification'), ('INTRO', 'Introduction to Coaching Football (Level 1)'), ('UEFA_C', 'UEFA C Licence (Level 2)'), ('UEFA_B', 'UEFA B Licence (Level 3)'), ('UEFA_A', 'UEFA A Licence (Level 4)'), ('UEFA_PRO', 'UEFA Pro Licence (Level 5)')], default='NONE', help_text='Highest coaching qualification held.', max_length=20),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='qualification_verified',
            field=models.BooleanField(default=False, help_text='Whether the coaching qualification has been verified by admin.'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Win percentage (e.g., 65.50 for 65.5%).', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='QualificationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('NONE', 'No Formal Qualification'), ('INTRO', 'Introduction to Coaching Football (Level 1)'), ('UEFA_C', 'UEFA C Licence (Level 2)'), ('UEFA_B', 'UEFA B Licence (Level 3)'), ('UEFA_A', 'UEFA A Licence (Level 4)'), ('UEFA_PRO', 'UEFA Pro Licence (Level 5)')], help_text='Type of qualification being verified.', max_length=20)),
                ('certificate_image', models.ImageField(help_text='Upload a photo/scan of your coaching certificate.', upload_to='coaching_certificates/')),
                ('fa_fan_number', models.CharField(blank=True, help_text='Optional: FA FAN (Football Affiliate Number).', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on the verification decision.')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='users.managerprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
