# Generated by Django 5.2 on 2026-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_managerprofile_coaching_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to the club's logo image.", max_length=500),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official club website URL.', max_length=500),
        ),
    ]
