# Generated by Django 5.2 on 2026-02-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clubprofile_logo_url_clubprofile_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Official name of the club (e.g., 'Halesowen Town FC').", max_length=100, unique=True)),
                ('league_level', models.CharField(choices=[('STEP_1', 'Step 1 (National League)'), ('STEP_2', 'Step 2 (National League North/South)'), ('STEP_3', 'Step 3 (Isthmian/Northern/Southern Premier)'), ('STEP_4', 'Step 4 (Isthmian/Northern/Southern Division One)'), ('STEP_5', 'Step 5 (Regional Leagues)'), ('STEP_6', 'Step 6 (County Leagues)'), ('STEP_7', 'Step 7 (Local Leagues)'), ('SUNDAY', 'Sunday League'), ('OTHER', 'Other')], default='SUNDAY', help_text='League level the club plays in.', max_length=10)),
                ('website_url', models.URLField(blank=True, help_text='Official club website URL.', max_length=500)),
                ('rss_url', models.URLField(blank=True, help_text='RSS feed URL for automatic news scraping.', max_length=500)),
                ('logo_url', models.URLField(blank=True, help_text="URL to the club's logo image.", max_length=500)),
                ('region', models.CharField(default='Birmingham', help_text="Region/city (e.g., 'Birmingham', 'West Midlands').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Club Source (RSS)',
                'verbose_name_plural': 'Club Sources (RSS)',
                'ordering': ['league_level', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='newsitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='club',
            field=models.ForeignKey(blank=True, help_text='The registered club (for user-posted content).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='users.clubprofile'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(help_text='Link to the full news article.', max_length=1000, unique=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The RSS club source (for aggregated content).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='users.clubsource'),
        ),
    ]
