# Generated by Django 5.2 on 2026-02-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clubsource_alter_newsitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('GENERAL', 'General Update'), ('ACHIEVEMENT', 'Achievement'), ('MATCH_REPORT', 'Match Report'), ('TRAINING', 'Training Session'), ('HIGHLIGHT', 'Highlight Video'), ('MILESTONE', 'Career Milestone'), ('TRANSFER', 'Transfer News'), ('AWARD', 'Award/Recognition')], default='GENERAL', help_text='Type of post (achievement, match report, etc.)', max_length=20)),
                ('caption', models.TextField(help_text='Post caption/description', max_length=1000)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the post', null=True, upload_to='post_images/')),
                ('video', models.FileField(blank=True, help_text='Upload a video (MP4, AVI, MOV). Max size: 100MB', null=True, upload_to='post_videos/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video link', max_length=500)),
                ('goals', models.IntegerField(blank=True, help_text='Goals scored', null=True)),
                ('assists', models.IntegerField(blank=True, help_text='Assists provided', null=True)),
                ('clean_sheets', models.IntegerField(blank=True, help_text='Clean sheets (for goalkeepers)', null=True)),
                ('minutes_played', models.IntegerField(blank=True, help_text='Minutes played in the match', null=True)),
                ('match_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Match rating (e.g., 8.5)', max_digits=3, null=True)),
                ('match_opponent', models.CharField(blank=True, help_text='Opponent team name', max_length=100)),
                ('match_result', models.CharField(blank=True, help_text="Match result (e.g., 'Won 3-1', 'Drew 2-2')", max_length=20)),
                ('match_date', models.DateField(blank=True, help_text='Date of the match', null=True)),
                ('competition', models.CharField(blank=True, help_text="Competition name (e.g., 'FA Cup', 'League Cup')", max_length=100)),
                ('award_title', models.CharField(blank=True, help_text='Award or milestone title', max_length=200)),
                ('award_description', models.TextField(blank=True, help_text='Award or milestone description', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, help_text='Users who liked this post', related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
