# Generated by Django 5.2 on 2026-02-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='areas_for_improvement',
            field=models.TextField(blank=True, help_text='Areas where player can improve', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='coaching_methodology',
            field=models.TextField(blank=True, help_text='Coaching methodology or training approach', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='player_age',
            field=models.IntegerField(blank=True, help_text='Age of scouted player', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='player_club',
            field=models.CharField(blank=True, help_text='Current club of scouted player', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='player_position',
            field=models.CharField(blank=True, help_text='Position of scouted player', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='player_scouted',
            field=models.CharField(blank=True, help_text='Name of player scouted', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='potential_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Potential rating (out of 10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scouting_report',
            field=models.TextField(blank=True, help_text='Detailed scouting report or assessment', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='strengths',
            field=models.TextField(blank=True, help_text="Player's key strengths", max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='tactical_analysis',
            field=models.TextField(blank=True, help_text='Tactical analysis or coaching insights (for managers)', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='team_formation',
            field=models.CharField(blank=True, help_text='Formation used (e.g., 4-3-3, 3-5-2)', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='team_performance',
            field=models.TextField(blank=True, help_text='Team performance summary', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('GENERAL', 'General Update'), ('ACHIEVEMENT', 'Achievement'), ('MATCH_REPORT', 'Match Report'), ('TRAINING', 'Training Session'), ('HIGHLIGHT', 'Highlight Video'), ('MILESTONE', 'Career Milestone'), ('TRANSFER', 'Transfer News'), ('AWARD', 'Award/Recognition'), ('TACTICAL', 'Tactical Analysis'), ('COACHING', 'Coaching Insights'), ('TEAM_NEWS', 'Team News'), ('PLAYER_REPORT', 'Player Scouting Report'), ('TALENT_SPOT', 'Talent Spotting')], default='GENERAL', help_text='Type of post (achievement, match report, etc.)', max_length=20),
        ),
    ]
