# Generated by Django 5.2 on 2026-02-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_areas_for_improvement_post_coaching_methodology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_applications', to='users.opportunity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_applications', to='users.playerprofile')),
            ],
            options={
                'verbose_name': 'Trial Application',
                'verbose_name_plural': 'Trial Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('player', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='TrialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1, help_text='Number of times this player viewed this trial.')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_views', to='users.opportunity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_views', to='users.playerprofile')),
            ],
            options={
                'verbose_name': 'Trial View',
                'verbose_name_plural': 'Trial Views',
                'ordering': ['-viewed_at'],
                'unique_together': {('player', 'opportunity')},
            },
        ),
    ]
