# Generated by Django 5.2 on 2026-02-28 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_trialapplication_trialview'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by an official club manager'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this opportunity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
