# Generated by Django 5.2 on 2026-03-02 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_opportunity_is_verified_opportunity_verified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualificationverification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Coaching Licence Verification', 'verbose_name_plural': 'Coaching Licence Verifications'},
        ),
        migrations.AddField(
            model_name='qualificationverification',
            name='dashboard_screenshot',
            field=models.ImageField(blank=True, default='', help_text='Upload a screenshot from your England Football Learning dashboard showing your name, FAN number, and licence level. This is required for cross-verification.', upload_to='coaching_dashboard_screenshots/'),
        ),
        migrations.AddField(
            model_name='qualificationverification',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection. This IS visible to the manager so they can resubmit.'),
        ),
        migrations.AddField(
            model_name='qualificationverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='The admin who reviewed this verification request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_licences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualificationverification',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes on the verification decision. NOT visible to the user.'),
        ),
        migrations.AlterField(
            model_name='qualificationverification',
            name='certificate_image',
            field=models.ImageField(help_text='Upload a clear photo or scan of your coaching certificate (PDF or image). Your full name and qualification level must be visible.', upload_to='coaching_certificates/'),
        ),
        migrations.AlterField(
            model_name='qualificationverification',
            name='fa_fan_number',
            field=models.CharField(default='', help_text='Your FA FAN (Football Affiliate Number). This is required for cross-reference against your dashboard screenshot.', max_length=50),
        ),
        migrations.AlterField(
            model_name='qualificationverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Fazz Pitchside Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Further Review')], default='PENDING', max_length=20),
        ),
    ]
