# Generated by Django 5.2 on 2026-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_qualificationverification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationverification',
            name='certificate_image',
            field=models.FileField(help_text='Upload a clear photo, scan, or PDF of your coaching certificate. Your full name and qualification level must be visible.', upload_to='coaching_certificates/'),
        ),
    ]
