# Generated by Django 5.2 on 2026-03-03 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_qualificationverification_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutprofile',
            name='scout_verified',
            field=models.BooleanField(default=False, help_text='Whether this scout has been verified by the platform.'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='verification_tier',
            field=models.CharField(blank=True, choices=[('TIER1', 'FAZZ Verified Scout'), ('TIER2', 'FAZZ Advanced Verified'), ('TIER3', 'FAZZ Professional Verified')], help_text='Verified tier awarded by admin.', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_body', models.CharField(choices=[('FA', 'The Football Association (FA)'), ('PFSA', 'Professional Football Scouts Association (PFSA)'), ('OTHER', 'Other Recognised Course'), ('NONE', 'No Formal Qualification')], help_text='Awarding body for the qualification.', max_length=10)),
                ('qualification_level', models.CharField(choices=[('FA_L1', 'FA Level 1 – Introduction to Talent ID'), ('FA_L2', 'FA Level 2 – National Talent ID & Scouting'), ('FA_L3', 'FA Level 3 – Advanced Principles of Talent ID'), ('FA_L4', 'FA Level 4 – Leadership of Talent ID'), ('FA_L5', 'FA Level 5 – Technical Directors Course'), ('PFSA_L1', 'PFSA Level 1 – Talent ID'), ('PFSA_L2', 'PFSA Level 2 – Talent ID'), ('PFSA_L3', 'PFSA Level 3 – Talent ID'), ('PFSA_OPP', 'PFSA Opposition Analysis'), ('PFSA_TECH', 'PFSA Technical Scouting'), ('OTHER', 'Other Recognised Course'), ('NONE', 'No Formal Qualification')], help_text='Level of qualification being verified.', max_length=20)),
                ('fa_fan_number', models.CharField(blank=True, help_text='FA FAN number (required for FA qualifications).', max_length=20, null=True)),
                ('certificate_file', models.FileField(help_text='Upload your qualification certificate (PDF or image).', upload_to='scout_certificates/')),
                ('dashboard_screenshot', models.ImageField(blank=True, help_text='England Football dashboard screenshot (FA route only).', null=True, upload_to='scout_dashboards/')),
                ('safeguarding_certificate', models.FileField(blank=True, help_text='Safeguarding certificate (required for Tier 2+).', null=True, upload_to='scout_safeguarding/')),
                ('dbs_expiry_date', models.DateField(blank=True, help_text='DBS certificate expiry date (required for Tier 2+).', null=True)),
                ('club_affiliation_proof', models.FileField(blank=True, help_text='Signed club letter or official club email (Tier 3).', null=True, upload_to='scout_club_proof/')),
                ('sample_scout_report', models.FileField(blank=True, help_text='Sample anonymised scout report (Tier 3).', null=True, upload_to='scout_reports/')),
                ('requested_tier', models.CharField(choices=[('TIER1', 'FAZZ Verified Scout'), ('TIER2', 'FAZZ Advanced Verified'), ('TIER3', 'FAZZ Professional Verified')], default='TIER1', help_text='Tier the scout is applying for.', max_length=10)),
                ('awarded_tier', models.CharField(blank=True, choices=[('TIER1', 'FAZZ Verified Scout'), ('TIER2', 'FAZZ Advanced Verified'), ('TIER3', 'FAZZ Professional Verified')], help_text='Tier actually awarded by admin (may differ from requested).', max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Further Review')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes (not visible to scout).')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to scout on rejection.')),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='users.scoutprofile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='The admin who reviewed this verification request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scout Verification',
                'verbose_name_plural': 'Scout Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
