# Generated by Django 5.2 on 2026-03-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_scoutprofile_scout_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('trial', 'Trial News'), ('general', 'General News'), ('transfer', 'Transfer News'), ('match', 'Match Reports')], default='general', help_text='Category of the news item.', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('verification', 'Verification Update'), ('follow', 'New Follower'), ('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Request Accepted'), ('like', 'Post Liked'), ('message', 'New Message'), ('opportunity', 'New Opportunity'), ('system', 'System Notification')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contract_type',
            field=models.CharField(choices=[('AMATEUR', 'Amateur'), ('SEMI_PRO', 'Semi-Professional'), ('EXPENSES', 'Expenses Only'), ('PAID', 'Paid'), ('UNSPECIFIED', 'Not Specified')], default='UNSPECIFIED', max_length=15),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='level_required',
            field=models.CharField(blank=True, help_text='e.g. Step 3-4, Sunday League, County League', max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='positions_needed',
            field=models.CharField(blank=True, help_text='Comma-separated list of positions needed', max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available — Actively Looking'), ('OPEN', 'Open to Offers'), ('CONTRACTED', 'Contracted — Not Available'), ('TRIALLING', 'Currently on Trial'), ('INJURED', 'Unavailable — Injured')], default='AVAILABLE', help_text='Current availability status.', max_length=15),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short professional bio shown on your profile', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, only approved followers can see full profile.'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_club', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='users.clubprofile')),
                ('opportunity', models.ForeignKey(blank=True, help_text='Optional — link shortlist to a specific trial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.opportunity')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='users.playerprofile')),
            ],
            options={
                'unique_together': {('club', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_notes', models.TextField(blank=True, help_text='Private scout notes — never shown to player')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='users.playerprofile')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='users.scoutprofile')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('scout', 'player')},
            },
        ),
    ]
