# Generated by Django 5.2 on 2026-03-03 17:24

from django.db import migrations


def convert_availability(apps, schema_editor):
    PlayerProfile = apps.get_model('users', 'PlayerProfile')
    PlayerProfile.objects.filter(available_for_club=True).update(availability_status='AVAILABLE')
    PlayerProfile.objects.filter(available_for_club=False).update(availability_status='CONTRACTED')


def reverse_availability(apps, schema_editor):
    PlayerProfile = apps.get_model('users', 'PlayerProfile')
    PlayerProfile.objects.filter(availability_status__in=['AVAILABLE', 'OPEN', 'TRIALLING']).update(available_for_club=True)
    PlayerProfile.objects.filter(availability_status__in=['CONTRACTED', 'INJURED']).update(available_for_club=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_newsitem_category_notification_action_url_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_availability, reverse_availability),
    ]
