# Generated by Django 5.2 on 2026-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('verification', 'Verification Update'), ('follow', 'New Follower'), ('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Request Accepted'), ('like', 'Post Liked'), ('comment', 'Comment'), ('message', 'New Message'), ('opportunity', 'New Opportunity'), ('system', 'System Notification')], default='system', max_length=20),
        ),
    ]
