# Generated by Django 5.2 on 2026-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_comment_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='ai_recruitment_score',
            field=models.IntegerField(default=0, help_text='AI-generated recruitment intent score (0-100). Higher = more likely recruiting.'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated explanation of why this article was flagged as a recruitment signal.'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('trial', 'Trial News'), ('general', 'General News'), ('transfer', 'Transfer News'), ('match', 'Match Reports'), ('recruitment_signal', 'Recruitment Signals')], default='general', help_text='Category of the news item.', max_length=20),
        ),
    ]
