# Generated by Django 5.2 on 2026-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_newsitem_ai_recruitment_score_newsitem_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth. Must be at least 16 years old.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', help_text='Token for email verification link.', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email address.'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='User consented to privacy policy and data processing at signup.'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_consent_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user gave consent.', null=True),
        ),
    ]
