# Generated by Django 5.2 on 2026-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_playerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutprofile',
            name='is_scout_public',
            field=models.BooleanField(default=False, help_text='If True, others can see this account is a Scout. If False (default), the role is hidden.'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth. Must be at least 18 years old.', null=True),
        ),
    ]
