# Generated by Django 5.1.1 on 2026-03-24 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community_guidelines_consent',
            field=models.BooleanField(default=False, help_text='User agreed to community guidelines and code of conduct at signup.'),
        ),
        migrations.AddField(
            model_name='user',
            name='community_guidelines_consent_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user agreed to community guidelines.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='If True, user is temporarily suspended and cannot post or comment.'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, help_text='When the suspension ends. Null if not suspended.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for current or most recent suspension.'),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of warnings issued to this user for guideline violations.'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('USER', 'User Profile'), ('MESSAGE', 'Direct Message')], help_text='Type of content being reported.', max_length=20)),
                ('reason', models.CharField(choices=[('HARASSMENT', 'Harassment or Bullying'), ('HATE_SPEECH', 'Hate Speech or Discrimination'), ('SPAM', 'Spam or Misleading Content'), ('INAPPROPRIATE', 'Inappropriate or Offensive Content'), ('FAKE_ACCOUNT', 'Fake Account or Impersonation'), ('SCAM', 'Scam or Fraudulent Activity'), ('VIOLENCE', 'Violence or Threatening Behaviour'), ('PERSONAL_INFO', 'Sharing Personal Information (Doxxing)'), ('COPYRIGHT', 'Copyright or Intellectual Property Violation'), ('OTHER', 'Other Violation')], help_text='Category of the violation.', max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the issue from the reporter.', max_length=2000)),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot as evidence.', null=True, upload_to='reports/screenshots/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_TAKEN', 'Action Taken'), ('DISMISSED', 'Dismissed - No Violation'), ('DUPLICATE', 'Duplicate Report')], default='PENDING', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority level (1=Low, 2=Medium, 3=High, 4=Critical)')),
                ('action_taken', models.CharField(choices=[('NONE', 'No Action Required'), ('WARNING', 'Warning Issued'), ('CONTENT_REMOVED', 'Content Removed'), ('SUSPENDED_24H', 'User Suspended (24 Hours)'), ('SUSPENDED_7D', 'User Suspended (7 Days)'), ('SUSPENDED_30D', 'User Suspended (30 Days)'), ('BANNED', 'User Permanently Banned')], default='NONE', help_text='Action taken by admin in response to this report.', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin reference. Not visible to reporter.')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes sent to reporter about the resolution (optional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_comment', models.ForeignKey(blank=True, help_text='The comment being reported (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.comment')),
                ('reported_post', models.ForeignKey(blank=True, help_text='The post being reported (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.post')),
                ('reported_user', models.ForeignKey(blank=True, help_text='The user being reported (for USER reports or content owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who submitted this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_repor_status_b7e575_idx'), models.Index(fields=['reported_user', 'status'], name='users_repor_reporte_13ecfd_idx')],
            },
        ),
    ]
