# Generated by Django 5.2 on 2026-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_saved_post_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='clubsource',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload the official club logo.', null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='clubsource',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload the official club logo.', null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', help_text='Profile picture for the user.', null=True, upload_to='profile_pictures/'),
        ),
    ]
