# Generated by Django 5.2 on 2026-07-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_clubprofile_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Technical, Tactical, Physical, Coaching', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Users mentioned in the post body', related_name='mentioned_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='trending_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated score for trending algorithms', max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, help_text='Hashtags used in the post', related_name='posts', to='users.hashtag'),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='managers', to='users.skill'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='players', to='users.skill'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='scouts', to='users.skill'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', 'Like'), ('FIRE', 'Fire'), ('CLAP', 'Clap'), ('SUPPORT', 'Support')], default='LIKE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='users.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorsed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_endorsements', to=settings.AUTH_USER_MODEL)),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='users.skill')),
            ],
            options={
                'unique_together': {('skill', 'endorsed_user', 'endorser')},
            },
        ),
    ]
